---

- name: Install unzip
  package:
    name: unzip
    state: present

- name: Download and unarchive TestLink
  unarchive: 
    src: https://github.com/TestLinkOpenSourceTRMS/testlink-code/archive/testlink_1_9_20_fixed.zip
    dest: /var/www/
    remote_src: yes

- name: Rename the Testlink directory
  command: mv /var/www/testlink-code-testlink_1_9_20_fixed/ /var/www/testlink
  ignore_errors: True

- name: Change directory (gui/templates_c) ownership, group, and permissions
  file:
    path: /var/www/testlink/gui/templates_c
    owner: nginx
    group: nginx
    mode: '0777'

- name: Create a directory (/var/testlink)
  file:
    path: /var/testlink
    state: directory
    mode: '0777'

- name: Create a directory (/var/testlink/logs)
  file:
    path: /var/testlink/logs
    state: directory
    mode: '0777'

- name: Create a directory (/var/testlink/upload_area)
  file:
    path: /var/testlink/upload_area
    state: directory
    mode: '0777'

- name: Change directory (/var/lib/php/session) group apache -> nginx
  file:
    path: /var/lib/php/session
    group: nginx

- name: Change directory (/var/lib/php/wsdlcache) group apache -> nginx
  file:
    path: /var/lib/php/wsdlcache
    group: nginx

- name: Change directory (/var/lib/php/opcache) group apache -> nginx
  file:
    path: /var/lib/php/opcache
    group: nginx

- name: Backup default config.inc.php configuration
  shell: /bin/cp /var/www/testlink/config.inc.php /var/www/testlink/config.inc.php.bak
  args:
    creates: /var/www/testlink/config.inc.php.bak

- name: Change config.inc.php warning mode to "SILENT"
  lineinfile:
    path: /var/www/testlink/config.inc.php
    regexp: 'config_check_warning_mode'
    line: $tlCfg->config_check_warning_mode = 'SILENT';
  notify:
  - Restart php-fpm

- name: Modify php.ini to optimize max_execution_time configuration for TestLink
  ini_file:
    path: /etc/php.ini
    section: PHP
    option: max_execution_time
    value: '120'
  notify:
  - Restart php-fpm

- name: Modify php.ini to optimize session.gc_maxlifetime configuration for TestLink
  ini_file:
    path: /etc/php.ini
    section: Session
    option: session.gc_maxlifetime
    value: '2400'
  notify:
  - Restart php-fpm

- name: Modify php.ini to set max_input_vars = 1000 for TestLink
  lineinfile:
    path: /etc/php.ini
    regexp: 'max_input_vars'
    line: max_input_vars = 1000
  notify:
  - Restart php-fpm

- name: Modify php.ini to set date.timezone = 'America/Los_Angeles'
  ini_file:
    path: /etc/php.ini
    section: Date
    option: date.timezone
    value: 'America/Los_Angeles'
  notify:
  - Restart php-fpm

- name: Create TestLink database
  mysql_db:
    login_user: root
    login_password: "{{ mysql_password }}"
    name: testlink
    collation: "utf8_general_ci"
    encoding: "utf8"
    state: present

- name: Create TestLink tables (execute sql script)
  mysql_db:
    login_user: root
    login_password: "{{ mysql_password }}"
    state: import
    name: testlink
    target: /var/www/testlink/install/sql/mysql/testlink_create_tables.sql
  ignore_errors: True

- name: Create TestLink default data (execute sql script)
  mysql_db:
    login_user: root
    login_password: "{{ mysql_password }}"
    state: import
    name: testlink
    target: /var/www/testlink/install/sql/mysql/testlink_create_default_data.sql
  ignore_errors: True

- name: Change an example db to 'testlink' in udf0 sql script
  replace:
    path: /var/www/testlink/install/sql/mysql/testlink_create_udf0.sql
    regexp: 'YOUR_TL_DBNAME'
    replace: 'testlink'

- name: SET GLOBAL log_bin_trust_function_creators = 1; in udf0 sql script
  mysql_variables:
    login_user: root
    login_password: "{{ mysql_password }}"
    variable: log_bin_trust_function_creators
    value: "1"
  ignore_errors: True

- name: Create TestLink udf0 (execute sql script)
  mysql_db:
    login_user: root
    login_password: "{{ mysql_password }}"
    state: import
    name: testlink
    target: /var/www/testlink/install/sql/mysql/testlink_create_udf0.sql
  ignore_errors: True
