---

- name: Disable SELinux
  selinux:
    state: disabled

- name: Reboot the machine
  shell: sleep 5 && systemctl reboot
  async: 300
  poll: 0
 
- name: Wait for system to come back online
  wait_for_connection:
    delay: 60
    timeout: 300
